sudo: required
language: bash
git:
  depth: 1
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y build-essential libncurses5-dev rsync cpio python unzip bc wget
install:
  - make intel_ich10_defconfig
script:
  - make 
